// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://biyhrxrumyvwtwonlbwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpeWhyeHJ1bXl2d3R3b25sYndxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyMDY0NDYsImV4cCI6MjA3Njc4MjQ0Nn0.Gr1JGt02hfXE7e-i5rCvvIFlXKdhtZ7urlnmKAEkHoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});